listmatkul = [
    'Pancasila',
    'Social and Professional Skills II',
    'Data Structures',
    'Programming II',
    'Statistics II for Computer Science',
    'English II',
    'Technopreneurship',
    'Linear Algebra for Computer Science',
    'Analisa & Perancangan Sistem',
    'Operating Systems',
    'Cloud Computing',
    'Algorithms Analysis',
    'Software Engineering',
    'Computer Architecture',
    'Data Mining',
    'Computer Security',
    'Database II',
    'eCommerce',
    'Financial Analysis(Electives)',
    'Pemograman Java lanjut',
    'Mobile Programming',
    'Dasar Router',
    'Tata Kelola Tl',
    'Etika Profesi',
    'Sistem Penunjang Keputusan',
    'Manajemen & Strategi Bisnis'
]

# print (listmatkul)
